import { useEffect, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { Download, Printer, Copy, QrCode as QrCodeIcon } from 'lucide-react';
import { Card, Badge, StarRating, EmptyState } from '../../components/ui';
import { Button } from '../../components/Button';
import { kioskApi, authApi, KioskSession } from '../../lib/api';
import { useActiveLocation } from '../../lib/useLocation';
import { branding } from '../../config/branding';
import { useToast } from '../../lib/toast';

export default function KioskSessionsPage() {
  const { locationId } = useActiveLocation();
  const { showSuccess } = useToast();
  const [sessions, setSessions] = useState<KioskSession[]>([]);
  const [loading, setLoading] = useState(true);
  const [businessName, setBusinessName] = useState('');
  const [qrDataUrl, setQrDataUrl] = useState('');
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const kioskUrl = locationId
    ? `${window.location.origin}/kiosk?location=${locationId}&name=${encodeURIComponent(businessName || 'us')}`
    : '';

  useEffect(() => {
    if (!locationId) return;
    (async () => {
      setLoading(true);
      const [{ sessions }, meRes] = await Promise.all([
        kioskApi.listForLocation(locationId),
        authApi.me().catch(() => null),
      ]);
      setSessions(sessions.sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)));
      if (meRes?.business?.name) setBusinessName(meRes.business.name);
      setLoading(false);
    })();
  }, [locationId]);

  useEffect(() => {
    if (!kioskUrl) return;
    QRCode.toDataURL(kioskUrl, { width: 400, margin: 2, color: { dark: '#16171A', light: '#FFFFFF' } })
      .then(setQrDataUrl)
      .catch(() => {});
  }, [kioskUrl]);

  function downloadQr() {
    const a = document.createElement('a');
    a.href = qrDataUrl;
    a.download = `${(businessName || 'review-qr').replace(/\s+/g, '-').toLowerCase()}-qr.png`;
    a.click();
  }

  function printQr() {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head><title>Review QR — ${businessName}</title></head>
        <body style="text-align:center; font-family: sans-serif; padding: 40px;">
          <h2>${businessName}</h2>
          <p>Scan to leave a review</p>
          <img src="${qrDataUrl}" style="width:300px;height:300px;" />
          <script>window.onload = () => window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  function copyLink() {
    navigator.clipboard.writeText(kioskUrl);
    showSuccess('Link copied.');
  }

  if (!locationId) {
    return <EmptyState title="No business connected" body="Connect a business in Settings first." />;
  }

  const total = sessions.length;
  const posted = sessions.filter((s) => s.posted).length;
  const avg = total ? (sessions.reduce((s, r) => s + r.rating, 0) / total).toFixed(1) : '—';

  return (
    <div className="p-5 md:p-8 max-w-3xl mx-auto">
      <h1 className="font-display text-2xl font-semibold mb-1">Kiosk Reviews</h1>
      <p className="text-sm text-ink-soft mb-6">Every draft a customer generated by scanning your QR code.</p>

      <Card className="mb-6">
        <h2 className="font-semibold text-sm mb-3 flex items-center gap-1.5">
          <QrCodeIcon className="w-4 h-4" /> Your review QR code
        </h2>
        <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center">
          {qrDataUrl && (
            <img src={qrDataUrl} alt="Review QR code" className="w-32 h-32 border border-line rounded-lg" />
          )}
          <div className="flex-1">
            <p className="text-xs text-ink-soft mb-3">
              Print this and put it on the counter, table tents, or receipts — checkout counter tends to get
              the highest scan rate.
            </p>
            <div className="flex flex-wrap gap-2">
              <Button size="sm" onClick={downloadQr} disabled={!qrDataUrl}>
                <Download className="w-3.5 h-3.5" /> Download PNG
              </Button>
              <Button size="sm" variant="secondary" onClick={printQr} disabled={!qrDataUrl}>
                <Printer className="w-3.5 h-3.5" /> Print
              </Button>
              <Button size="sm" variant="ghost" onClick={copyLink}>
                <Copy className="w-3.5 h-3.5" /> Copy link
              </Button>
            </div>
          </div>
        </div>
      </Card>

      <div className="grid grid-cols-3 gap-4 mb-6">
        <Card><div className="font-display text-2xl font-semibold">{total}</div><div className="text-xs text-ink-soft">Total drafts</div></Card>
        <Card><div className="font-display text-2xl font-semibold">{posted}</div><div className="text-xs text-ink-soft">Posted</div></Card>
        <Card><div className="font-display text-2xl font-semibold">{avg}</div><div className="text-xs text-ink-soft">Avg. rating</div></Card>
      </div>

      {loading ? (
        <p className="text-sm text-ink-soft">Loading...</p>
      ) : sessions.length === 0 ? (
        <EmptyState title="No kiosk drafts yet" body="These appear once a customer scans your QR code and generates a review." />
      ) : (
        <div className="space-y-3">
          {sessions.map((s) => (
            <Card key={s.id}>
              <div className="flex items-start justify-between gap-3 mb-2">
                <StarRating value={s.rating} readOnly size={16} />
                <div className="flex items-center gap-2">
                  <Badge tone={s.posted ? 'success' : 'neutral'}>{s.posted ? 'Posted' : 'Draft only'}</Badge>
                  <span className="text-xs text-ink-soft">{new Date(s.createdAt).toLocaleDateString()}</span>
                </div>
              </div>
              <p className="text-sm leading-relaxed">{s.editedDraft || s.aiDraft}</p>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
